### ISSUE TITLE
Feature Request: Custom role names

### ISSUE THREAD

**Issue by ballwood** [functionalone/serverless-iam-roles-per-function#2]
Hi,

Just a quick feature request - custom role names for each function. The serverless role names generated from the default lambda role seem to have so much in them sometimes when we deploy a longer stage name the build fails :-(. Would be good to be able to shorten them a bit!

Cheers for the plugin, it’s helped us a lot so far...don’t know why it isn’t a core feature of serverless! :)

**Comment by yKarakita** [comment]
Hi, I have same problem. It would be good to be able to custom each role names too!

**Comment by glicht** [comment]
Hi,

Thanks for the feedback. Just to understand, are the errors you are seeing as a result of the role name exceeding the AWS role name limit (If I am not mistaken this limit is 64 chars)? If so, sounds like the plugin should at least do a sanity check on the generated name length and break early as a start.

Would adding a field of the sort: `iamRoleStatementsName` where you can specify the name is what you are after?

Another option I see, is providing a global configuration which provides some control how these names are generated. Currently the plugin is using the serverless framework's naming convention with an added "function name" after the stage section in the name.

**Comment by ballwood** [comment]
Yeah it seems to be the 64 character limit on AWS: getting the error  'roleName' failed to satisfy constraint: Member must have length less than or equal to 64. 

Either of the solutions would be good 👍 , I'd be leaning towards iamRoleStatementsName maybe as its more declarative in the serverless.yml file?

**Comment by glicht** [comment]
I've just published version 0.1.3 with support for defining a custom name via `iamRoleStatementsName` property. Also, put in a validation to fail early if the default generated role name is longer than 64 chars.
