### ISSUE TITLE
PermissionBoundary support

### ISSUE THREAD

**Issue by thiagoananias** [functionalone/serverless-iam-roles-per-function#27]
Hello!

I would like to have PermissionsBoundary property so i could limit what the roles are able to create. What do you guys think?

**Comment by thiagoananias** [comment]
I found on this blog post https://blog.smirnov.la/how-to-control-permission-of-iam-role-created-within-cloudformation-stack-d2ac975ecc80

And this official one: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html

**Comment by justinlazaro-iselect** [comment]
having an issue here, can i ask how do you implement it? @thiagoananias

**Comment by thiagoananias** [comment]
Hello! Feature Permissions Boundary #67 solves my problem!

**Comment by Enase** [comment]
@thiagoananias Could you add function [schema validation]?(https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema).
You can find it [here](https://github.com/functionalone/serverless-iam-roles-per-function/blob/v3.0.2/src/lib/index.ts#L54).

**Comment by Enase** [comment]
closed by https://github.com/functionalone/serverless-iam-roles-per-function/pull/68
