### ISSUE TITLE
Missing logs:CreateLogGroup permission

### ISSUE THREAD

**Issue by mickael-coquer** [functionalone/serverless-iam-roles-per-function#36]
Hi guys,

It seems that you should add the logs:CreateLogGroup permission as in the AWSLambdaBasicExecutionRole policy so that Lambda does not complain about it:

![image](https://user-images.githubusercontent.com/46025989/71483006-e202c000-2805-11ea-8ff4-dd5c52862c7d.png)

Servless Framework had the same issue: https://github.com/serverless/serverless/issues/6241.

Note that this is not a blocker as Lambda can still write logs in CloudWatch but it might an issue later on?

**Comment by daaru00** [comment]
Hi all,

is there a plan to solve this issue? The linked PR seems can solve it but it cannot be included directly (being written in TypeScript is not possible to directly link a branch from npm). 
It would be nice to merge the PR and close this issue, it's been a long time since it opened without feedback..

**Comment by BartusZak** [comment]
Hellow everybody,

Faced the same issue with missing `Allow: logs:CreateLogGroup` policy today.

I was wondering to add it mannually and then checked issues tab. 
Please merge that PR so we can eliminate that lack of permissions.

**Comment by kclay** [comment]
Ran into this issue so created a plugin with the aid of https://github.com/functionalone/serverless-iam-roles-per-function/pull/42

```js
class Plugin {
    constructor(serverless, options) {
        this.serverless = serverless;
        this.options = options;

        this.aws = this.serverless.getProvider('aws');
        this.serverlessLog = serverless.cli.log.bind(serverless.cli);

        this.hooks = {
            'before:package:finalize': this.fixIamRoles.bind(this),
        };
    }
    fixIamRoles() {
        //https://github.com/functionalone/serverless-iam-roles-per-function/issues/36
        const allFunctions = this.serverless.service.getAllFunctions();

        for (const functionName of allFunctions) {
            const functionObject = this.serverless.service.getFunction(functionName);

            if (functionObject.iamRoleStatements === undefined) {
                continue;
            }
            const globalRoleName = this.serverless.providers.aws.naming.getRoleLogicalId();
            const roleResourceName =
                this.serverless.providers.aws.naming.getNormalizedFunctionName(functionName) + globalRoleName;
            const functionIamRole = this.serverless.service.provider.compiledCloudFormationTemplate.Resources[
                roleResourceName
            ];
            const Action = functionIamRole.Properties.Policies[0].PolicyDocument.Statement[0].Action;
            if (!Action.includes('logs:CreateLogGroup')) {
                Action.push('logs:CreateLogGroup');
            }
        }
    }
}
module.exports = Plugin;
```

Create a `.serverless_plugins` folder and add the file there. I gave it the name `add-create-log-group-permission.js`

Then declare the plugin AFTER `serverless-iam-roles-per-function`
```yaml
plugins:
  - serverless-iam-roles-per-function
  - add-create-log-group-permission
```

**Comment by Enase** [comment]
fixed by https://github.com/functionalone/serverless-iam-roles-per-function/pull/42
