### ISSUE TITLE
The provided execution role does not have permissions to call PutTraceSegments on XRAY 

### ISSUE THREAD

**Issue by jani937** [functionalone/serverless-iam-roles-per-function#39]
Hi,
I ran into the issue after integrating **'serverless-iam-roles-per-function**' plugin and I'm moving everything over to per-function roles, but when I run sls deploy I get an error from CloudFormation saying that

_ServerlessError: An error occurred: ProcessESDataLoadEventLambdaFunction - The provided execution role does not have permissions to call PutTraceSegments on XRAY (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 1d48ba9f-4e02-42df-8587-fe4b872d2161)._

However, i see CF has below details auto generated.
`***********************************************************
              {
                  "Effect": "Allow",
                  "Action": [
                    "xray:PutTraceSegments",
                    "xray:PutTelemetryRecords"
                  ],
                  "Resource": [
                    "*"
                  ]
                }
***********************************************************
`

`
Below is my lambda function looks like after moving roles per function:

lamdbafuncitonexample:
  handler: src/functions/**handler
  tags: ${self:custom.tags}
  description: Process event received from changed sqs queue
  iamRoleStatementsName:
    Fn::Join:
      - '-'
      - - ${self:custom.Prefix}
        - 'lamdbafuncitonexample'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: ${self:custom.resources.topic}
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource:
        Fn::Join:
          - ':'
          - - 'arn:aws:secretsmanager'
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - secret
            - 'credential-**'
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource:
        Fn::Join:
          - ':'
          - - 'arn:aws:secretsmanager'
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - secret
            - 'credential-**'

  # Define the trigger for the lambda function here
  events:
    - sqs:
        arn: ${self:custom.resources.SQS}`

**Comment by bisoldi** [comment]
Ran into this as well.  Serverless.yml file below:

https://gist.github.com/bisoldi/27564bb8de3f93399c61778e07f25fee

It appears to not work when enabling xray tracing via `tracing: lambda: true ` in the provider block.  Haven't tried it with the xray tracing plugin, but simply adding PutTraceSegments permission as an inherited permission in the provider block solved it.
