### ISSUE TITLE
Versions 3.0.2 and 3.1.0

### ISSUE THREAD

**Issue by ankon** [functionalone/serverless-iam-roles-per-function#69]
There are:
- https://www.npmjs.com/package/serverless-iam-roles-per-function/v/3.0.2-fb28ee6
- https://www.npmjs.com/package/serverless-iam-roles-per-function/v/3.0.2-223021
- https://www.npmjs.com/package/serverless-iam-roles-per-function/v/3.1.0-d68046e (also tagged as `next`)

Given that 3.0.2 and 3.1.0 appear in the changelog and have tags in github I assumed these would be released already, but I might be misunderstanding the intent/flow of the changelog/github tags/npm version?

**Comment by ankon** [comment]
3.0.2 contains a rather critical fix, without which this plugin is quite problematic to use (#42).

@glicht you released 3.0.2 with https://github.com/functionalone/serverless-iam-roles-per-function/commit/fb28ee6b4dc25f2a160b148b7f23bf5358e73aa4, could you maybe check whether something went wrong there?

**Comment by ankon** [comment]
Work-around for anyone needing #42: Depend on `^3.0.2-fb28ee6` in package.json.

**Comment by glicht** [comment]
@ankon the package is not released immediately after a PR is merged to master. It is first released as pre-release version (available via the `next` tag). Once confidence is high an official release is done to npmjs. More about this process here: https://github.com/functionalone/serverless-iam-roles-per-function#publishing-a-production-release-maintainers

As 3.1.0 has been out for a while I am going to release it.
