### ISSUE TITLE
Deprecation warning: provider.iamRoleStatements" -> "provider.iam.role.statements

### ISSUE THREAD

**Issue by asgoth** [functionalone/serverless-iam-roles-per-function#73]
Serverless starts showing deprecation warning messages:

    Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
                "provider.iamRoleStatements" -> "provider.iam.role.statements"
                More Info: https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS

Migrating to the new property is not possible, because `custom.serverless-iam-roles-per-function.defaultInherit` only looks for `provider.iamRoleStatements`. 

See https://github.com/functionalone/serverless-iam-roles-per-function/blob/master/src/lib/index.ts#L347

**Comment by glicht** [comment]
@asgoth thanks for reporting this. 

Looking for contributor help here. If anyone wants to try to handle this with a PR, I will try to assist with pushing the PR in.

**Comment by randomhash** [comment]
Can we simply skip it, and forget about warning? Do we need to migrate over their new feature? It's not a problem for us that serverless will not know this props 
Maybe we can simply add new props and if there is nothing check old ones I guess, will take a look a this in few weeks

**Comment by circulon** [comment]
> Can we simply skip it, and forget about warning? Do we need to migrate over their new feature? It's not a problem for us that serverless will not know this props
> Maybe we can simply add new props and if there is nothing check old ones I guess, will take a look a this in few weeks

+1 

A big yes to Checking for the new props and then the old if empty. 
I was bitten by this exact issue this week where I upgraded the provider section but as this plugin does not know about the new structure, so my functions did not receive the default role statements from the provider section as expected.

**Comment by gdraynz** [comment]
Looks like this has been released but not on `npm` ? any insight on that ?

**Comment by LironEr** [comment]
@Enase @glicht any update on 3.2.0(https://github.com/functionalone/serverless-iam-roles-per-function/pull/78) release? 

@gdraynz you can download `3.2.0-e97ab49` version from npm until the official `3.2.0` will be released
